# Generated by Django 3.1.6 on 2022-07-21 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('topBottom', models.CharField(blank=True, choices=[('top', 'top'), ('bottom', 'bottom')], max_length=10)),
                ('concepts', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('steps', models.TextField()),
                ('comments', models.TextField()),
                ('position', models.ManyToManyField(related_name='position_name', to='bjjtracker.Position')),
                ('tags', models.ManyToManyField(blank=True, to='bjjtracker.Tag')),
            ],
        ),
    ]
