# Generated by Django 3.1.6 on 2022-07-25 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('concepts', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('topBottom', models.CharField(blank=True, choices=[('top', 'top'), ('bottom', 'bottom')], max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('steps', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjjtracker.position')),
                ('tags', models.ManyToManyField(blank=True, to='bjjtracker.Tag')),
            ],
        ),
    ]
