# Generated by Django 3.1.6 on 2022-07-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjjtracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='topBottom',
        ),
        migrations.AddField(
            model_name='technique',
            name='topBottom',
            field=models.CharField(blank=True, choices=[('top', 'top'), ('bottom', 'bottom')], max_length=10),
        ),
    ]
