# Generated by Django 3.1.6 on 2022-07-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjjtracker', '0002_auto_20220721_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
