# Generated by Django 4.0.6 on 2022-08-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjjtracker', '0003_remove_motd_id_alter_motd_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
