# Generated by Django 4.0.6 on 2022-08-09 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bjjtracker', '0010_alter_technique_user_delete_motd'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOTD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bjjtracker.technique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('technique', 'user')},
            },
        ),
    ]
