# Generated by Django 4.0.6 on 2022-08-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjjtracker', '0012_alter_motd_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_trained', models.IntegerField()),
                ('numRolls', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
